import { h as head, e as escape_html, b as attr, i as stringify } from "../../../chunks/index2.js";
import { S as SiteNav } from "../../../chunks/SiteNav.js";
import { S as SITE_CONFIG } from "../../../chunks/modules.js";
function _page($$renderer, $$props) {
  $$renderer.component(($$renderer2) => {
    head("1e0rsuc", $$renderer2, ($$renderer3) => {
      $$renderer3.title(($$renderer4) => {
        $$renderer4.push(`<title>RE² — Terms of Service</title>`);
      });
    });
    SiteNav($$renderer2);
    $$renderer2.push(`<!----> <main class="svelte-1e0rsuc"><div class="container svelte-1e0rsuc"><h1 class="svelte-1e0rsuc">Terms of Service</h1> <p class="effective-date svelte-1e0rsuc">Effective Date: March 23, 2026 · Last Updated: March 23, 2026</p> <p class="intro svelte-1e0rsuc">Welcome to RE² ("we," "us," or "our"), operated by ${escape_html(SITE_CONFIG.company)}.
			By accessing or using the RE² platform at ${escape_html(SITE_CONFIG.domain)} (the "Service"),
			you agree to be bound by these Terms of Service ("Terms"). If you do not agree, do not use the Service.</p> <section class="svelte-1e0rsuc"><h2 class="svelte-1e0rsuc">1. Description of Service</h2> <p class="svelte-1e0rsuc">RE² is an AI-powered platform that provides location analysis, business modeling,
				financial projections, loan package preparation, and operational tools for prospective
				retail and food-service business owners. The Service uses artificial intelligence,
				machine learning, and third-party data sources to generate analyses and recommendations.</p></section> <section class="svelte-1e0rsuc"><h2 class="svelte-1e0rsuc">2. Beta Disclaimer</h2> <p class="svelte-1e0rsuc"><strong>RE² is currently in beta.</strong> The platform is provided on an "as-is" and
				"as-available" basis. Features may change, data may be incomplete, and analyses may
				contain errors. We are actively improving the platform and appreciate your feedback.</p></section> <section class="svelte-1e0rsuc"><h2 class="svelte-1e0rsuc">3. Not Professional Advice</h2> <p class="highlight svelte-1e0rsuc"><strong>IMPORTANT:</strong> RE² does NOT provide financial advice, legal advice, real estate
				brokerage services, investment advice, or accounting services. All scores, projections,
				recommendations, and analyses generated by the platform are for informational and educational
				purposes only. They should not be relied upon as the sole basis for any business, financial,
				or legal decision.</p> <p class="svelte-1e0rsuc">You should consult with qualified professionals — including a licensed attorney, accountant,
				commercial real estate broker, and financial advisor — before signing any lease, taking out
				any loan, or making any business commitment.</p></section> <section class="svelte-1e0rsuc"><h2 class="svelte-1e0rsuc">4. No Guarantees</h2> <p class="svelte-1e0rsuc">We do not guarantee the accuracy, completeness, reliability, or timeliness of any information
				provided through the Service. Location scores, financial projections, business models, and
				recommendations are generated using AI models and publicly available data, which may contain
				inaccuracies or become outdated. Past performance indicators do not guarantee future results.</p></section> <section class="svelte-1e0rsuc"><h2 class="svelte-1e0rsuc">5. User Accounts</h2> <p class="svelte-1e0rsuc">You must create an account to access the Service. You are responsible for maintaining the
				confidentiality of your login credentials and for all activity under your account. You agree
				to provide accurate information during registration and to update it as needed.</p></section> <section class="svelte-1e0rsuc"><h2 class="svelte-1e0rsuc">6. Acceptable Use</h2> <p class="svelte-1e0rsuc">You agree not to: (a) use the Service for any unlawful purpose; (b) attempt to reverse-engineer,
				decompile, or extract source code from the Service; (c) scrape, crawl, or automatically extract
				data from the Service; (d) share your account credentials with third parties; (e) use the Service
				to generate misleading materials for loan applications or investor pitches.</p></section> <section class="svelte-1e0rsuc"><h2 class="svelte-1e0rsuc">7. Intellectual Property</h2> <p class="svelte-1e0rsuc">All content, features, functionality, branding, and technology of the Service are owned by
				${escape_html(SITE_CONFIG.company)} and are protected by applicable intellectual property laws. "RE²," "Location Einstein," "Space Einstein," "Business Einstein," "Loan Einstein," "Launch Einstein,"
				"E=MC²," and "Einstein" as used in the platform are trademarks of ${escape_html(SITE_CONFIG.company)}.</p></section> <section class="svelte-1e0rsuc"><h2 class="svelte-1e0rsuc">8. User Data and Content</h2> <p class="svelte-1e0rsuc">You retain ownership of any data you input into the Service (business plans, financial information,
				uploaded documents). By using the Service, you grant us a limited license to process this data
				solely for the purpose of providing the Service to you. We will not sell your data to third parties.
				See our <a href="/privacy" class="svelte-1e0rsuc">Privacy Policy</a> for details.</p></section> <section class="svelte-1e0rsuc"><h2 class="svelte-1e0rsuc">9. Limitation of Liability</h2> <p class="legal-caps svelte-1e0rsuc">TO THE MAXIMUM EXTENT PERMITTED BY LAW, JARED CLAW LLC AND ITS OFFICERS, DIRECTORS, EMPLOYEES,
				AND AGENTS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE
				DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, BUSINESS OPPORTUNITIES, OR DATA, ARISING
				OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICE. <strong>OUR TOTAL LIABILITY SHALL NOT EXCEED
				THE AMOUNT YOU PAID US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR $100, WHICHEVER IS GREATER.</strong></p></section> <section class="svelte-1e0rsuc"><h2 class="svelte-1e0rsuc">10. Indemnification</h2> <p class="svelte-1e0rsuc">You agree to indemnify and hold harmless ${escape_html(SITE_CONFIG.company)} from any claims, damages, losses, or
				expenses arising from your use of the Service, your violation of these Terms, or your reliance
				on any information provided by the Service.</p></section> <section class="svelte-1e0rsuc"><h2 class="svelte-1e0rsuc">11. Disclaimers on AI-Generated Content</h2> <p class="svelte-1e0rsuc">The Service uses artificial intelligence (including large language models) to generate analyses,
				projections, recommendations, and documents. AI-generated content may contain errors,
				hallucinations, or outdated information. You are solely responsible for reviewing and verifying
				all AI-generated output before relying on it for any purpose.</p></section> <section class="svelte-1e0rsuc"><h2 class="svelte-1e0rsuc">12. Third-Party Services</h2> <p class="svelte-1e0rsuc">The Service may integrate with or reference third-party services (including but not limited to
				Clerk for authentication, mapping services for location data, and financial data providers).
				We are not responsible for the accuracy, availability, or practices of third-party services.</p></section> <section class="svelte-1e0rsuc"><h2 class="svelte-1e0rsuc">13. Modifications</h2> <p class="svelte-1e0rsuc">We may update these Terms at any time. Material changes will be communicated via email or
				in-app notification. Continued use of the Service after changes constitutes acceptance of
				the updated Terms.</p></section> <section class="svelte-1e0rsuc"><h2 class="svelte-1e0rsuc">14. Termination</h2> <p class="svelte-1e0rsuc">We may suspend or terminate your access at any time for violation of these Terms or for any
				other reason at our sole discretion. You may delete your account at any time by contacting us.</p></section> <section class="svelte-1e0rsuc"><h2 class="svelte-1e0rsuc">15. Governing Law</h2> <p class="svelte-1e0rsuc">These Terms are governed by the laws of the State of New York, without regard to conflict of
				law principles. Any disputes shall be resolved in the courts of New York County, New York.</p></section> <section class="svelte-1e0rsuc"><h2 class="svelte-1e0rsuc">16. Contact</h2> <p class="svelte-1e0rsuc">Questions about these Terms? Contact us at: <a${attr("href", `mailto:${stringify(SITE_CONFIG.emails.support)}`)} class="svelte-1e0rsuc">${escape_html(SITE_CONFIG.emails.support)}</a></p></section></div></main>`);
  });
}
export {
  _page as default
};
