<script>
	import SiteNav from '$lib/components/SiteNav.svelte';
	import { SITE_CONFIG } from '$lib/modules';
</script>

<svelte:head>
	<title>RE² — Terms of Service</title>
</svelte:head>

<SiteNav />

<main>
	<div class="container">
		<h1>Terms of Service</h1>
		<p class="effective-date">Effective Date: March 23, 2026 · Last Updated: March 23, 2026</p>

		<p class="intro">
			Welcome to RE² ("we," "us," or "our"), operated by {SITE_CONFIG.company}.
			By accessing or using the RE² platform at {SITE_CONFIG.domain} (the "Service"),
			you agree to be bound by these Terms of Service ("Terms"). If you do not agree, do not use the Service.
		</p>

		<section>
			<h2>1. Description of Service</h2>
			<p>
				RE² is an AI-powered platform that provides location analysis, business modeling,
				financial projections, loan package preparation, and operational tools for prospective
				retail and food-service business owners. The Service uses artificial intelligence,
				machine learning, and third-party data sources to generate analyses and recommendations.
			</p>
		</section>

		<section>
			<h2>2. Beta Disclaimer</h2>
			<p>
				<strong>RE² is currently in beta.</strong> The platform is provided on an "as-is" and
				"as-available" basis. Features may change, data may be incomplete, and analyses may
				contain errors. We are actively improving the platform and appreciate your feedback.
			</p>
		</section>

		<section>
			<h2>3. Not Professional Advice</h2>
			<p class="highlight">
				<strong>IMPORTANT:</strong> RE² does NOT provide financial advice, legal advice, real estate
				brokerage services, investment advice, or accounting services. All scores, projections,
				recommendations, and analyses generated by the platform are for informational and educational
				purposes only. They should not be relied upon as the sole basis for any business, financial,
				or legal decision.
			</p>
			<p>
				You should consult with qualified professionals — including a licensed attorney, accountant,
				commercial real estate broker, and financial advisor — before signing any lease, taking out
				any loan, or making any business commitment.
			</p>
		</section>

		<section>
			<h2>4. No Guarantees</h2>
			<p>
				We do not guarantee the accuracy, completeness, reliability, or timeliness of any information
				provided through the Service. Location scores, financial projections, business models, and
				recommendations are generated using AI models and publicly available data, which may contain
				inaccuracies or become outdated. Past performance indicators do not guarantee future results.
			</p>
		</section>

		<section>
			<h2>5. User Accounts</h2>
			<p>
				You must create an account to access the Service. You are responsible for maintaining the
				confidentiality of your login credentials and for all activity under your account. You agree
				to provide accurate information during registration and to update it as needed.
			</p>
		</section>

		<section>
			<h2>6. Acceptable Use</h2>
			<p>
				You agree not to: (a) use the Service for any unlawful purpose; (b) attempt to reverse-engineer,
				decompile, or extract source code from the Service; (c) scrape, crawl, or automatically extract
				data from the Service; (d) share your account credentials with third parties; (e) use the Service
				to generate misleading materials for loan applications or investor pitches.
			</p>
		</section>

		<section>
			<h2>7. Intellectual Property</h2>
			<p>
				All content, features, functionality, branding, and technology of the Service are owned by
				{SITE_CONFIG.company} and are protected by applicable intellectual property laws. "RE²," "Location Einstein," "Space Einstein," "Business Einstein," "Loan Einstein," "Launch Einstein,"
				"E=MC²," and "Einstein" as used in the platform are trademarks of {SITE_CONFIG.company}.
			</p>
		</section>

		<section>
			<h2>8. User Data and Content</h2>
			<p>
				You retain ownership of any data you input into the Service (business plans, financial information,
				uploaded documents). By using the Service, you grant us a limited license to process this data
				solely for the purpose of providing the Service to you. We will not sell your data to third parties.
				See our <a href="/privacy">Privacy Policy</a> for details.
			</p>
		</section>

		<section>
			<h2>9. Limitation of Liability</h2>
			<p class="legal-caps">
				TO THE MAXIMUM EXTENT PERMITTED BY LAW, JARED CLAW LLC AND ITS OFFICERS, DIRECTORS, EMPLOYEES,
				AND AGENTS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE
				DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, BUSINESS OPPORTUNITIES, OR DATA, ARISING
				OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICE. <strong>OUR TOTAL LIABILITY SHALL NOT EXCEED
				THE AMOUNT YOU PAID US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR $100, WHICHEVER IS GREATER.</strong>
			</p>
		</section>

		<section>
			<h2>10. Indemnification</h2>
			<p>
				You agree to indemnify and hold harmless {SITE_CONFIG.company} from any claims, damages, losses, or
				expenses arising from your use of the Service, your violation of these Terms, or your reliance
				on any information provided by the Service.
			</p>
		</section>

		<section>
			<h2>11. Disclaimers on AI-Generated Content</h2>
			<p>
				The Service uses artificial intelligence (including large language models) to generate analyses,
				projections, recommendations, and documents. AI-generated content may contain errors,
				hallucinations, or outdated information. You are solely responsible for reviewing and verifying
				all AI-generated output before relying on it for any purpose.
			</p>
		</section>

		<section>
			<h2>12. Third-Party Services</h2>
			<p>
				The Service may integrate with or reference third-party services (including but not limited to
				Clerk for authentication, mapping services for location data, and financial data providers).
				We are not responsible for the accuracy, availability, or practices of third-party services.
			</p>
		</section>

		<section>
			<h2>13. Modifications</h2>
			<p>
				We may update these Terms at any time. Material changes will be communicated via email or
				in-app notification. Continued use of the Service after changes constitutes acceptance of
				the updated Terms.
			</p>
		</section>

		<section>
			<h2>14. Termination</h2>
			<p>
				We may suspend or terminate your access at any time for violation of these Terms or for any
				other reason at our sole discretion. You may delete your account at any time by contacting us.
			</p>
		</section>

		<section>
			<h2>15. Governing Law</h2>
			<p>
				These Terms are governed by the laws of the State of New York, without regard to conflict of
				law principles. Any disputes shall be resolved in the courts of New York County, New York.
			</p>
		</section>

		<section>
			<h2>16. Contact</h2>
			<p>
				Questions about these Terms? Contact us at:
				<a href="mailto:{SITE_CONFIG.emails.support}">{SITE_CONFIG.emails.support}</a>
			</p>
		</section>
	</div>
</main>

<style scoped>
	:global(body) {
		background-color: var(--white);
		color: var(--text);
	}

	main {
		display: flex;
		justify-content: center;
		align-items: flex-start;
		padding: 80px 20px 60px 20px;
		min-height: 100vh;
	}

	.container {
		width: 100%;
		max-width: 800px;
	}

	h1 {
		font-size: 2.5rem;
		font-weight: 700;
		margin-bottom: 12px;
		color: var(--teal);
	}

	.effective-date {
		color: var(--text-secondary);
		margin-bottom: 20px;
		font-size: 0.95rem;
	}

	.intro {
		font-size: 1.05rem;
		line-height: 1.7;
		margin-bottom: 40px;
		color: var(--text);
	}

	section {
		margin-bottom: 40px;
	}

	h2 {
		font-size: 1.5rem;
		font-weight: 600;
		color: var(--teal);
		margin-bottom: 16px;
		margin-top: 32px;
	}

	p {
		line-height: 1.7;
		margin-bottom: 16px;
		font-size: 1rem;
	}

	a {
		color: var(--teal);
		text-decoration: none;
		border-bottom: 1px solid transparent;
		transition: border-bottom-color 0.2s;
	}

	a:hover {
		border-bottom-color: var(--teal);
	}

	.highlight {
		background-color: var(--teal-bg);
		border-left: 4px solid var(--teal);
		padding: 16px;
		margin: 24px 0;
		border-radius: 4px;
	}

	.legal-caps {
		font-size: 0.9rem;
		line-height: 1.8;
	}
</style>
