import { h as head, e as escape_html } from "../../../../chunks/index2.js";
import { loadLaunchPadData } from "../../../../chunks/launchpad-store.js";
function _page($$renderer, $$props) {
  $$renderer.component(($$renderer2) => {
    let lpData = loadLaunchPadData();
    head("oop0ou", $$renderer2, ($$renderer3) => {
      $$renderer3.title(($$renderer4) => {
        $$renderer4.push(`<title>RE² — About ${escape_html(lpData.businessName || "Your Business")}</title>`);
      });
    });
    $$renderer2.push(`<div class="about-page svelte-oop0ou"><section class="hero svelte-oop0ou"><div class="hero-content svelte-oop0ou"><h1 class="svelte-oop0ou">About ${escape_html(lpData.businessName || "Your Business")}</h1> <p class="tagline svelte-oop0ou">Fuel your purpose</p></div></section> <section class="section concept svelte-oop0ou"><div class="section-content svelte-oop0ou"><h2 class="svelte-oop0ou">The Concept</h2> <p class="svelte-oop0ou">${escape_html(lpData.visionStatement || "A wellness-first business offering differentiated products and services.")}</p></div></section> <section class="section pillars svelte-oop0ou"><div class="section-header svelte-oop0ou"><h2 class="svelte-oop0ou">The Three Pillars</h2></div> <div class="pillars-grid svelte-oop0ou"><div class="pillar svelte-oop0ou" style="--pillar-color: #FF2D55"><div class="pillar-icon svelte-oop0ou">⚡</div> <h3 class="svelte-oop0ou">ENERGIZE</h3> <p class="svelte-oop0ou">Energy and focus for your day. Our energizing blends combine premium coffee with adaptogens designed to provide sustained mental clarity without the crash.</p></div> <div class="pillar svelte-oop0ou" style="--pillar-color: #9D4EDD"><div class="pillar-icon svelte-oop0ou">✨</div> <h3 class="svelte-oop0ou">GLOW</h3> <p class="svelte-oop0ou">Self-care and vitality in every sip. Our glow collection features collagen-infused drinks and antioxidant-rich blends for radiant wellness from within.</p></div> <div class="pillar svelte-oop0ou" style="--pillar-color: #00E8CC"><div class="pillar-icon svelte-oop0ou">🧘</div> <h3 class="svelte-oop0ou">RESET</h3> <p class="svelte-oop0ou">Calm and relaxation when you need it. Our reset line includes adaptogens and botanical blends designed to soothe the nervous system and restore balance.</p></div></div></section> <section class="section location svelte-oop0ou"><div class="section-content svelte-oop0ou"><h2 class="svelte-oop0ou">Our Location</h2> <p class="location-text svelte-oop0ou"><strong>Your Primary Location</strong></p> <p class="location-desc svelte-oop0ou">Located in ${escape_html(lpData?.idealArea || "a prime neighborhood")}. A carefully curated space designed for
				wellness and community.</p></div></section> <section class="section menu svelte-oop0ou"><div class="section-content svelte-oop0ou"><h2 class="svelte-oop0ou">The Menu</h2> <div class="menu-overview svelte-oop0ou"><p class="svelte-oop0ou"><strong>74 SKUs</strong> spanning:</p> <ul class="menu-list svelte-oop0ou"><li class="svelte-oop0ou">Protein lattes</li> <li class="svelte-oop0ou">Collagen drinks</li> <li class="svelte-oop0ou">Kids menu</li> <li class="svelte-oop0ou">Grab-and-go food</li> <li class="svelte-oop0ou">5 daily bundles</li></ul></div></div></section> <section class="section team svelte-oop0ou"><div class="section-content svelte-oop0ou"><h2 class="svelte-oop0ou">The Team</h2> <p class="team-intro svelte-oop0ou">Our founders and team members bring years of expertise in wellness, business, and community building.</p> <div class="team-members svelte-oop0ou"><div class="team-placeholder svelte-oop0ou"><div class="placeholder-icon svelte-oop0ou">👥</div> <p class="svelte-oop0ou">Add your team members here</p> <button class="btn-secondary svelte-oop0ou">${escape_html("Add Team Member")}</button></div></div> `);
    {
      $$renderer2.push("<!--[-1-->");
    }
    $$renderer2.push(`<!--]--></div></section> <section class="section contact svelte-oop0ou"><div class="section-content svelte-oop0ou"><h2 class="svelte-oop0ou">Get in Touch</h2> <div class="contact-grid svelte-oop0ou"><div class="contact-item svelte-oop0ou"><div class="contact-label svelte-oop0ou">Website</div> <a href="https://resquared.io" target="_blank" class="contact-value svelte-oop0ou">resquared.io</a></div> <div class="contact-item svelte-oop0ou"><div class="contact-label svelte-oop0ou">Email</div> <a href="mailto:hello@resquared.io" class="contact-value svelte-oop0ou">hello@resquared.io</a></div></div></div></section></div>`);
  });
}
export {
  _page as default
};
